rgbd_odometry:
  ros__parameters:
    qos_overrides:
      '/camera/rgbd/camera_info':
        subscription:
          reliability: best_effort
          history: keep_last
          depth: 1
          durability: volatile

      "/camera/rgbd/image":
        subscription:
          reliability: best_effort
          history: keep_last
          depth: 1
          durability: volatile
      
      '/camera/rgbd/depth_image':
        subscription:
          reliability: best_effort
          history: keep_last
          depth: 1
          durability: volatile