# This file is used by the gazebo_ros_bridge plugin to configure topic bridges between ROS 2 and Gazebo

# Clock topic
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# gz topic published by JointState plugin
- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# gz topic subscribed to by motor driver plugin
- ros_topic_name: "cmd_vel"
  gz_topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ


# gz topic published by IMU plugin
- ros_topic_name: "imu"
  gz_topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (LIDAR)
- ros_topic_name: "scan"
  gz_topic_name: "scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (LIDAR)
- ros_topic_name: "points"
  gz_topic_name: "points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# gz topic published by RGB Camera
- ros_topic_name: "camera/rgb/image_raw"
  gz_topic_name: "camera/rgb/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "camera/rgb/camera_info"
  gz_topic_name: "camera/rgb/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Depth Camera
- ros_topic_name: "camera/depth/depth_image"
  gz_topic_name: "camera/depth/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# This publishes ok, but it off in the wrong frame (optical frame, not pointcloud frame)
#- ros_topic_name: "camera/depth/depth_image/points"
#  gz_topic_name: "camera/depth/depth_image/points"
#  ros_type_name: "sensor_msgs/msg/PointCloud2"
#  gz_type_name: "gz.msgs.PointCloudPacked"
#  direction: GZ_TO_ROS

- ros_topic_name: "camera/depth/camera_info"
  gz_topic_name: "camera/depth/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# gz topic published by Pointcloud Camera
# all in frame_id "pointcloud_frame" (which is incorrectly oriented,
# see https://github.com/gazebosim/gz-sensors/issues/29#issuecomment-3113732696)

#- ros_topic_name: "camera/pointcloud/image"
#  gz_topic_name: "camera/pointcloud/image"
#  ros_type_name: "sensor_msgs/msg/Image"
#  gz_type_name: "gz.msgs.Image"
#  direction: GZ_TO_ROS

#- ros_topic_name: "camera/pointcloud/depth_image"
#  gz_topic_name: "camera/pointcloud/depth_image"
#  ros_type_name: "sensor_msgs/msg/Image"
#  gz_type_name: "gz.msgs.Image"
#  direction: GZ_TO_ROS

- ros_topic_name: "camera/pointcloud/points"
  gz_topic_name: "camera/pointcloud/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

- ros_topic_name: "camera/pointcloud/camera_info"
  gz_topic_name: "camera/pointcloud/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS